[project]
name = "mm_head"
version = "0.0.1"
description = "量筒的密室杀手配套脚本"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "deepdiff>=9.1.0",
    "pillow>=12.3.0",
    "requests>=2.34.2",
]

[tool.ruff.format]
quote-style = "single"

[dependency-groups]
dev = [
    "pylint>=4.0.8",
]
